import React, { useState, useRef, useEffect, useCallback } from 'react';

const PRACTICE_SONGS = [
  { id: 1, title: 'Somewhere Over the Rainbow',
    artist: 'Israel Kamakawiwo\'ole',
    difficulty: 'Beginner',
    key: 'C',
    bpm: 66,
    chords: ['C', 'F', 'G', 'Em', 'Am'],
    lyrics: [
      { text: "Oooooooo ooooo ooooo ooooo", chord: 'C', beats: 8 },
      { text: "Somewhere over the rainbow", chord: null, beats: 4 },
      { text: "Way up high", chord: 'F', beats: 4 },
      { text: "There's a land that I heard of", chord: 'G', beats: 4 },
      { text: "Once in a lullaby", chord: 'Em', beats: 4 },
      { text: "Somewhere over the rainbow", chord: 'Am', beats: 4 },
      { text: "Skies are blue", chord: 'C', beats: 4 },
      { text: "And the dreams that you dare to dream", chord: null, beats: 4 },
      { text: "Really do come true", chord: 'F', beats: 4 },
      { text: "Someday I'll wish upon a star", chord: 'G', beats: 4 },
      { text: "And wake up where the clouds are far behind me", chord: 'Em', beats: 4 },
      { text: "Where trouble melts like lemon drops", chord: 'Am', beats: 4 },
      { text: "High above the chimney top", chord: 'C', beats: 4 },
      { text: "That's where you'll find me", chord: null, beats: 4 },
      { text: "Oooooooo ooooo ooooo ooooo", chord: 'F', beats: 8 },
      { text: "Somewhere over the rainbow", chord: 'G', beats: 4 },
      { text: "Bluebirds fly", chord: 'Em', beats: 4 },
      { text: "Birds fly over the rainbow", chord: 'Am', beats: 4 },
      { text: "Why then oh why can't I?", chord: 'C', beats: 4 },
      { text: "If happy little bluebirds fly", chord: null, beats: 4 },
      { text: "Beyond the rainbow", chord: 'F', beats: 4 },
      { text: "Why oh why can't I?", chord: 'G', beats: 4 },
      { text: "Well I see trees of green", chord: 'Em', beats: 4 },
      { text: "Red roses too", chord: 'Am', beats: 4 },
      { text: "I see them bloom", chord: 'C', beats: 4 },
      { text: "For me and you", chord: null, beats: 4 },
      { text: "And I think to myself", chord: 'F', beats: 4 },
      { text: "What a wonderful world", chord: 'G', beats: 4 },
      { text: "Well I see skies of blue", chord: 'Em', beats: 4 },
      { text: "And I see clouds of white", chord: 'Am', beats: 4 },
      { text: "And the brightness of day", chord: 'C', beats: 4 },
      { text: "I like the dark", chord: null, beats: 4 },
      { text: "And I think to myself", chord: 'F', beats: 4 },
      { text: "What a wonderful world", chord: 'G', beats: 4 },
      { text: "The colors of the rainbow", chord: 'Em', beats: 4 },
      { text: "So pretty in the sky", chord: 'Am', beats: 4 },
      { text: "Are also on the faces", chord: 'C', beats: 4 },
      { text: "Of people going by", chord: null, beats: 4 },
      { text: "I see friends shaking hands", chord: 'F', beats: 4 },
      { text: "Saying how do you do", chord: 'G', beats: 4 },
      { text: "They're really saying", chord: 'Em', beats: 4 },
      { text: "I I love you", chord: 'Am', beats: 4 },
      { text: "I hear babies cry", chord: 'C', beats: 4 },
      { text: "I watch them grow", chord: null, beats: 4 },
      { text: "They'll learn much more", chord: 'F', beats: 4 },
      { text: "Than we'll ever know", chord: 'G', beats: 4 },
      { text: "And I think to myself", chord: 'Em', beats: 4 },
      { text: "What a wonderful world", chord: 'Am', beats: 4 },
      { text: "Someday I'll wish upon a star", chord: 'C', beats: 4 },
      { text: "And wake up where the clouds are far behind me", chord: null, beats: 4 },
      { text: "Where trouble melts like lemon drops", chord: 'F', beats: 4 },
      { text: "High above the chimney top", chord: 'G', beats: 4 },
      { text: "That's where you'll find me", chord: 'Em', beats: 4 },
      { text: "Oooooooo ooooo ooooo ooooo", chord: 'Am', beats: 8 },
      { text: "Somewhere over the rainbow", chord: 'C', beats: 4 },
      { text: "Way up high", chord: null, beats: 4 },
      { text: "And the dreams that you dare to dream", chord: 'F', beats: 4 },
      { text: "Really do come true", chord: 'G', beats: 4 },
    ]
  },
  { id: 2, title: 'You Are My Sunshine',
    artist: 'Traditional',
    difficulty: 'Beginner',
    key: 'C',
    bpm: 138,
    chords: ['C', 'F', 'G'],
lyrics: [
      { text: 'You are my sunshine', chord: 'C', beats: 4 },
      { text: 'My only sunshine', chord: 'F', beats: 4 },
      { text: 'You make me happy', chord: 'C', beats: 4 },
      { text: "When skies are gray", chord: 'G', beats: 4 },
      { text: "You'll never know dear", chord: 'C', beats: 4 },
      { text: 'How much I love you', chord: 'F', beats: 4 },
      { text: "Please don't take", chord: 'C', beats: 4 },
      { text: 'My sunshine away', chord: 'G', beats: 4 },
    ]
  },
  { id: 3, title: 'Let It Be',
    artist: 'The Beatles',
    difficulty: 'Beginner',
    key: 'C',
    bpm: 76,
    chords: ['C', 'G', 'Am', 'F'],
    lyrics: [
      { text: 'When I find myself in times of trouble', chord: 'C', beats: 4 },
      { text: 'Mother Mary comes to me', chord: 'G', beats: 4 },
      { text: 'Speaking words of wisdom', chord: 'Am', beats: 4 },
      { text: 'Let it be', chord: 'F', beats: 4 },
      { text: 'And in my hour of darkness', chord: 'C', beats: 4 },
      { text: 'She is standing right in front of me', chord: 'G', beats: 4 },
      { text: 'Speaking words of wisdom', chord: 'Am', beats: 4 },
      { text: 'Let it be', chord: 'F', beats: 4 },
    ]
  },
  { id: 4, title: 'House of Gold',
    artist: 'Twenty One Pilots',
    difficulty: 'Intermediate',
    key: 'G',
    bpm: 150,
    chords: ['G', 'C', 'Em', 'D'],
    lyrics: [
      { text: 'How do you think I\'m going to feel', chord: 'G', beats: 4 },
      { text: 'When I\'m coming home again', chord: 'C', beats: 4 },
      { text: 'Tell me tell me', chord: 'Em', beats: 4 },
      { text: 'What do you see when you look at me', chord: 'D', beats: 4 },
    ]
  },
  { id: 5, title: 'Stand By Me',
    artist: 'Ben E. King',
    difficulty: 'Intermediate',
    key: 'A',
    bpm: 120,
    chords: ['A', 'F#m', 'D', 'E'],
    lyrics: [
      { text: 'When the night has come', chord: 'A', beats: 4 },
      { text: 'And the land is dark', chord: 'F#m', beats: 4 },
      { text: 'And the moon is the only light we\'ll see', chord: 'D', beats: 4 },
      { text: 'No I won\'t be afraid', chord: 'E', beats: 4 },
    ]
  },
  { id: 6, title: 'Riptide',
    artist: 'Vance Joy',
    difficulty: 'Intermediate',
    key: 'Am',
    bpm: 158,
    chords: ['Am', 'G', 'C', 'F'],
    lyrics: [
      { text: 'I was scared of dentists and the dark', chord: 'Am', beats: 4 },
      { text: 'I was scared of pretty girls and Sunday mornings', chord: 'G', beats: 4 },
      { text: 'I was scared of little bits of paper in the park', chord: 'C', beats: 4 },
      { text: 'And I turned around and you were gone', chord: 'F', beats: 4 },
    ]
  },
  { id: 7, title: 'Thinking Out Loud',
    artist: 'Ed Sheeran',
    difficulty: 'Intermediate',
    key: 'D',
    bpm: 79,
    chords: ['Em', 'G', 'D', 'C'],
    lyrics: [
      { text: 'When your legs don\'t work like they used to before', chord: 'Em', beats: 4 },
      { text: 'And I can\'t sweep you off of your feet', chord: 'G', beats: 4 },
      { text: 'Will your mouth still remember the taste of my love', chord: 'D', beats: 4 },
      { text: 'Will your eyes still smile from your cheeks', chord: 'C', beats: 4 },
    ]
  },
  { id: 8, title: 'I\'m Yours',
    artist: 'Jason Mraz',
    difficulty: 'Beginner',
    key: 'B',
    bpm: 104,
    chords: ['B', 'E', 'G#m', 'F#'],
    lyrics: [
      { text: 'Well I\'ve been playing hard to get', chord: 'B', beats: 4 },
      { text: 'Time to make my heart bet', chord: 'E', beats: 4 },
      { text: 'I wanna be yours, pretty baby', chord: 'G#m', beats: 4 },
      { text: 'Don\'t you make me wait too long', chord: 'F#', beats: 4 },
    ]
  },
  { id: 9, title: 'Hotel California',
    artist: 'Eagles',
    difficulty: 'Intermediate',
    key: 'Am',
    bpm: 75,
    chords: ["Am", "E7", "G", "D", "F", "C", "Dm", "E7"],
    lyrics: [
      { text: "(Instrumental Intro - Fingerpicking Pattern)", chord: null, beats: 8 },
      { text: "Am: 4-3-2-1-2-1, 3-2-1", chord: "Am", beats: 4 },
      { text: "E7: 4-3-2-1-2-1", chord: "E7", beats: 4 },
      { text: "G: 4-3-2-1-2-1, 3-2-1", chord: "G", beats: 4 },
      { text: "D: 4-3-2-1-2-1", chord: "D", beats: 4 },
      { text: "F: 4-3-2-1-2-1, 3-2-1", chord: "F", beats: 4 },
      { text: "C: 4-3-2-1-2-1", chord: "C", beats: 4 },
      { text: "Dm: 4-3-2-1-2-1, 3-2-1", chord: "Dm", beats: 4 },
      { text: "E7: 4-3-2-1-2-1 (Let ring)", chord: "E7", beats: 8 },
      { text: "", chord: null, beats: 4 },
      { text: "On a dark desert highway", chord: "Am", beats: 4 },
      { text: "Cool wind in my hair", chord: "E7", beats: 4 },
      { text: "Warm smell of colitas", chord: "G", beats: 4 },
      { text: "Rising up through the air", chord: "D", beats: 4 },
      { text: "Up ahead in the distance", chord: "F", beats: 4 },
      { text: "I saw a shimmering light", chord: "C", beats: 4 },
      { text: "My head grew heavy and my sight grew dim", chord: "Dm", beats: 4 },
      { text: "I had to stop for the night", chord: "E7", beats: 4 },
      { text: "There she stood in the doorway", chord: "Am", beats: 4 },
      { text: "I heard the mission bell", chord: "E7", beats: 4 },
      { text: "And I was thinking to myself", chord: "G", beats: 4 },
      { text: "This could be heaven or this could be hell", chord: "D", beats: 4 },
      { text: "Then she lit up a candle", chord: "F", beats: 4 },
      { text: "And she showed me the way", chord: "C", beats: 4 },
      { text: "There were voices down the corridor", chord: "Dm", beats: 4 },
      { text: "I thought I heard them say", chord: "E7", beats: 4 },
      { text: "Welcome to the Hotel California", chord: "Am", beats: 4 },
      { text: "Such a lovely place (such a lovely place)", chord: "E7", beats: 4 },
      { text: "Such a lovely face", chord: "G", beats: 4 },
      { text: "Plenty of room at the Hotel California", chord: "D", beats: 4 },
      { text: "Any time of year (any time of year)", chord: "F", beats: 4 },
      { text: "You can find it here", chord: "C", beats: 4 },
      { text: "Her mind is Tiffany-twisted", chord: "Dm", beats: 4 },
      { text: "She got the Mercedes-Benz, uh", chord: "E7", beats: 4 },
      { text: "She got a lot of pretty, pretty boys", chord: "Am", beats: 4 },
      { text: "That she calls friends", chord: "E7", beats: 4 },
      { text: "How they danced in the courtyard", chord: "F", beats: 4 },
      { text: "Sweet summer sweat", chord: "Dm", beats: 4 },
      { text: "Some dance to remember", chord: "Am", beats: 4 },
      { text: "Some dance to forget", chord: "E7", beats: 4 },
      { text: "So I called up the captain", chord: "Am", beats: 4 },
      { text: '"Please bring me my wine"', chord: "E7", beats: 4 },
      { text: 'He said, "We haven\'t had that spirit here since 1969"', chord: "G", beats: 4 },
      { text: "And still those voices are calling from far away", chord: "D", beats: 4 },
      { text: "Wake you up in the middle of the night", chord: "F", beats: 4 },
      { text: "Just to hear them say", chord: "C", beats: 4 },
      { text: "Welcome to the Hotel California", chord: "Dm", beats: 4 },
      { text: "Such a lovely place (such a lovely place)", chord: "E7", beats: 4 },
      { text: "Such a lovely face", chord: "G", beats: 4 },
      { text: "They\'re livin\' it up at the Hotel California", chord: "D", beats: 4 },
      { text: "What a nice surprise (what a nice surprise)", chord: "F", beats: 4 },
      { text: "Bring your alibis", chord: "C", beats: 4 },
      { text: "Mirrors on the ceiling", chord: "Dm", beats: 4 },
      { text: "The pink champagne on ice", chord: "E7", beats: 4 },
      { text: 'And she said, "We are all just prisoners here"', chord: "Am", beats: 4 },
      { text: "Of our own device", chord: "E7", beats: 4 },
      { text: "And in the master\'s chambers", chord: "Am", beats: 4 },
      { text: "They gathered for the feast", chord: "E7", beats: 4 },
      { text: "They stab it with their steely knives", chord: "G", beats: 4 },
      { text: "But they just can\'t kill the beast", chord: "D", beats: 4 },
      { text: "Last thing I remember", chord: "F", beats: 4 },
      { text: "I was running for the door", chord: "C", beats: 4 },
      { text: "I had to find the passage back", chord: "Dm", beats: 4 },
      { text: "To the place I was before", chord: "E7", beats: 4 },
      { text: '"Relax, " said the night man', chord: "Am", beats: 4 },
      { text: "We are programmed to receive", chord: "E7", beats: 4 },
      { text: "But you can never leave", chord: "F", beats: 8 }
    ]
  },
];


function PracticeMode({ initialSongId, onDone }) {
  const [selectedSong, setSelectedSong] = useState(() => {
    if (initialSongId) {
      const found = PRACTICE_SONGS.find(s => s.id === initialSongId);
      return found || PRACTICE_SONGS[0];
    }
    return PRACTICE_SONGS[0];
  });
  const [currentIndex, setCurrentIndex] = useState(0);
  const [isPlaying, setIsPlaying] = useState(false);
  const [countdown, setCountdown] = useState(null);
  const [streak, setStreak] = useState(0);
  const [totalCorrect, setTotalCorrect] = useState(0);
  const [feedback, setFeedback] = useState(null);
  const [beatPulse, setBeatPulse] = useState(false);
  
  const audioCtxRef = useRef(null);
  const timerRef = useRef(null);
  const countdownRef = useRef(null);
  const lyricsContainerRef = useRef(null);
  const lineRefs = useRef([]);
  
  // If initialSongId changes (user picks a new song from SongLibrary), switch to it
};

export default PracticeMode;
export { PRACTICE_SONGS };
